[project]
name = "cli-docx2pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docx2pdf>=0.1.8",
    "psutil>=7.1.3",
    "pyinstaller>=6.17.0",
]
